apiVersion: v1
kind: ServiceAccount
metadata:
  name: port-executor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: port-executor
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: port-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: port-executor
subjects:
  - kind: ServiceAccount
    name: port-executor
