# Get an existing Port entity and use it's data in subsequent workflow templates
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: port.ci-get-and-print.0.0.1
  annotations:
spec:
  arguments:
    parameters:
  entrypoint: ci-tasks
  templates:
    - name: ci-tasks
      metadata:
        annotations:
      dag:
        tasks:
          - name: entity-get
            templateRef:
              name: port
              template: entity-get
            arguments:
              parameters:
                - name: PORT_CLIENT_ID
                  value: "YOUR_CLIENT_ID"
                - name: PORT_CLIENT_SECRET
                  value: "YOUR_CLIENT_SECRET"
                - name: BLUEPRINT_IDENTIFIER
                  value: "microservice" # Replace with your target blueprint identifier
                - name: ENTITY_IDENTIFIER
                  value: "morp" # Replace with your target entity identifier
          - name: log-info
            dependencies: [entity-get]
            template: log-info
            arguments:
              parameters:
                - name: INFO
                  value: "{{workflow.outputs.parameters.PORT_ENTITY_PROPERTIES}}"

    # This template will install JQ and print the `region` property of the Entity
    - name: log-info
      inputs:
        parameters:
          - name: INFO
      script:
        image: alpine:latest
        command: ["/bin/sh"]
        env:
          - name: INFO
            value: "{{ inputs.parameters.INFO }}"
        source: |
          set -e
          apk update 
          apk add jq
          echo ${INFO} | jq .region
